repo_url: https://github.com/Requisitos-de-Software/2024.1-Firefox/
repo_name: 2024.1-Firefox

site_name: Firefox
site_url: https://requisitos-de-software.github.io/2024.1-Firefox/
site_author: Grupo 06
site_description: Site destinado à apresentação do projeto de requisitos de software do Firefox

nav: 
  - Início: index.md
  - Atas: 
    - Reunião 27/03: atas/ata_27_03.md
    - Reunião 08/04: atas/ata_08_04.md
    - Reunião 15/04: atas/ata_15_04.md
  - Apresentações:
    - Apresentação 1: apresentacoes/apresentacao_1.md
    - Apresentação 2: apresentacoes/apresentacao_2.md
    - Apresentação 3: apresentacoes/apresentacao_3.md
  - Planejamento do projeto:
    - Heatmap: planejamento/heatmap.md
    - Cronograma: planejamento/cronograma.md
    - Ferramentas: planejamento/ferramentas.md
    - Contribuição: planejamento/contribuicao.md
    - Apps Avaliados: planejamento/apps_avaliados.md
    - App Escolhido: planejamento/app_escolhido.md
    - Termo de Uso: planejamento/termo_de_uso.md
    - Licença: planejamento/licenca.md
  - Pré-Rastreabilidade:
    - Rich Picture: pre-rastreabilidade/rich-picture.md
  - Elicitação de Requisitos:
    - Definição do Perfil de Usuário:
      - Análise de Documentos: elicitacao/perfil_usuario/analise_documento.md
      - Perfil de Usuário: elicitacao/perfil_usuario/perfil_de_usuario.md
      - Personas: elicitacao/personas/personas.md
    - Elicitação de Requisitos:
      - Técnicas:
        - Brainstorming: elicitacao/tecnicas/brainstorming.md
        - Entrevista: elicitacao/tecnicas/entrevista.md
        - Observação: elicitacao/tecnicas/observacao.md
        - Questionário: elicitacao/tecnicas/questionario.md
      - Requisitos Elicitados: elicitacao/tecnicas/requisitos_elicitados.md
    - Priorização de Requisitos: 
      - Técnicas: elicitacao/priorizacao/tecnicas_de_priorizacao.md
      - Requisitos Priorizados: elicitacao/priorizacao/requisitos_priorizados.md
  - Modelagem:
    - Léxicos: modelagem/lexicos/lexicos.md
    - Cenários: modelagem/cenarios.md
    - Casos de Uso: modelagem/casos_de_uso/casos_de_uso.md
    - Validação dos Casos de Uso: modelagem/casos_de_uso/valid_casos.md
    - Especificação Suplementar: modelagem/especificacao-suplementar.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para o modo escuro
      primary: orange
      accent: orange

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo claro
      primary: orange
      accent: orange


  language: pt-BR
  logo: images/firefox.png
  favicon: images/firefox.png
  extra_css: [stylesheets/extra.css]

plugins:
  - mermaid2